// <auto-generated />
using MetaBiliş.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetaBiliş.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260929230956_CoktanSecmeliSutunlar")]
    partial class CoktanSecmeliSutunlar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("MetaBiliş.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("MetaBiliş.Models.KullaniciCevabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EminlikPuani")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDogru")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoruId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerilenCevap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KullaniciCevaplari");
                });

            modelBuilder.Entity("MetaBiliş.Models.Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DogruCevap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecenekD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoruTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sorular");
                });

            modelBuilder.Entity("MetaBiliş.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Testler");
                });
#pragma warning restore 612, 618
        }
    }
}
